services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://clone-gymhark-api-production.up.railway.app/api/
    expose:
      - 5000     
    ports:
      - "5000:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
